services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    env_file:
      - ../location.env
    environment:
      - TZ=${TZ}
    volumes:
      - /volume1/docker/wallos/db:/var/www/html/db
      - /volume1/docker/wallos/logos:/var/www/html/images/uploads/logos
    ports:
      - "${HOST_PORT}:80/tcp"
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.name=Wallos
      - flame.url=${WALLOS_FLAME_URL}
      - flame.icon=dolphin
