services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1028
      - PGID=100
      - TZ=${TZ}
      - HARDCOVER_TOKEN=${HARDCOVER_API_KEY}
      - NETWORK_SHARE_MODE=true
    volumes:
      - /volume1/docker/calibre-web-automated/config:/config
      # This is an ingest dir, NOT a library one. Anything added here will be automatically added to your library according to the settings you have configured in CWA Settings page. All files placed here are REMOVED AFTER PROCESSING
      -  /volume1/docker/calibre-web-automated/ingest-temp:/cwa-book-ingest
      # If you don't have an existing library, CWA will automatically create one at the bind provided here
      - /volume1/data/library/Books:/calibre-library
    ports:
      - ${HOST_PORT}:8083
    restart: unless-stopped
