version: "3"
services:
  komga:
    container_name: komga
    image: gotson/komga:latest
    env_file:
      - ../location.env
    environment:
      - TZ=${TZ}
      - GUID=100
      - PUID=1028
    volumes:
      - /volume1/data/library/Manga:/manga:rw
      - /volume1/docker/komga/config:/config:rw
      - /volume1/docker/komga/data:/data:rw
    ports:
      - ${HOST_PORT}:25600
    restart: always
    labels:
      - flame.type=application
      - flame.name=Komga
      - flame.url=${FLAME_URL}
      - flame.icon=dog
