services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    env_file:
      - /volume1/docker/location.env
    environment:
      - TZ
      - LD_CONTAINER_NAME=linkding
      - LD_HOST_PORT=9090
      - LD_HOST_DATA_DIR=/volume1/docker/linkding/data
      - LD_SUPERUSER_NAME=${SUPERUSER_NAME}
      - LD_SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - LD_DISABLE_BACKGROUND_TASKS=False
      - LD_DISABLE_URL_VALIDATION=False
      - LD_ENABLE_AUTH_PROXY=False
      - LD_DB_ENGINE=sqlite
    volumes:
      - /volume1/docker/linkding:/etc/linkding/data
    ports:
      - ${HOST_PORT}:9090
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.name=Linkding
      - flame.url=${FLAME_URL}
      - flame.icon=unicorn
